### ISSUE TITLE
T-REX documentation

### ISSUE THREAD

**Issue by camtheman256** [mit-dormcon/website#129]
- [x] document React components
- [ ] Make Python script more configurable

**Comment by gabrc52** [comment]
real

**Comment by dtemkin1** [comment]
The easiest way to do this might be to figure out how to write an OpenAPI spec for t-rex, then use [spotlight elements](https://docs.stoplight.io/docs/elements/d6a8ba3f3c186-stoplight-elements) to integrate it with docusaurus? Idea from here: https://docusaurus.io/feature-requests/p/api-documentation-swagger

**Comment by camtheman256** [comment]
yeah! ive messed with openapi before and seen spotlight elements in use, an openapi spec for t-rex could be a rly good idea

**Comment by dtemkin1** [comment]
Resolved by #448, we can expand on it by doing CSS stuff here or by just editing the spec in mit-dormcon/t-rex now :3

**Comment by dtemkin1** [comment]
CSS was annoying me so it should be better now https://dormcon.mit.edu/about/rex/

**Comment by gabrc52** [comment]
Slay!
