### ISSUE TITLE
Debounce search for REX events

### ISSUE THREAD

**Issue by camtheman256** [mit-dormcon/website#165]
REX search is kinda laggy because it searches through all the events with every new keystroke.

We should debounce the search events to wait a bit for no new events before we update the filter state. Lots of packages are available for doing this, we would just need to integrate it with React. Good example of that is here: https://dmitripavlutin.com/react-throttle-debounce/

**Comment by camtheman256** [comment]
I tried to take a stab at this, and it was so much harder than I imagined! Turns out the example linked doesn't work for controlled inputs (where the `value` prop is set), and various levels of clever indirection are needed. This article seems to break it down pretty well: https://www.developerway.com/posts/debouncing-in-react

**Comment by dtemkin1** [comment]
(i am so late but i just saw this lmao) could you use the `useDebounce` hook from [here](https://usehooks.com/usedebounce)? i can take a stab at it if you want
